version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: rental-service-app
        container_name: rental-service-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        container_name: rental-service-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: rental-service-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: rental-service-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
